name: Deploy Server

on:
  push:
    branches: main

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'
      
      - name: install python  packages
        run:
          python -m pip install --upgrade pip
      
      - name: execute script
        run:  python server/app.py

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main